
spring:
 profiles:
    active:
    - dev

    
     
   
---
spring: 
  profiles:
  - dev 
  datasource:
    url: jdbc:mysql://localhost:3306/deven
    username: root
    password: test
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    
---
spring: 
  profiles:
  - prod 
  datasource:
    url: jdbc:mysql://localhost:3306/prod
    username: root
    password: test
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  

   


